# conics - Python library for dealing with conics
#
# Copyright 2026 Sergiu Deitsch <sergiu.deitsch@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Sphinx-Gallery image scraper producing light and dark variants.

Furo switches between a light and a dark theme, but the figures generated by
Sphinx-Gallery are plain Matplotlib images that do not follow the reader's
theme choice. This scraper renders every figure twice, once with the default
(light) style and once with Matplotlib's ``dark_background`` style, and
embeds both using the ``only-light``/``only-dark`` classes that Furo already
toggles based on the active theme. The dark rendering is saved with a
transparent background rather than a hard-coded color so it blends into
whichever background Furo's dark theme happens to use.
"""

from __future__ import annotations

from sphinx_gallery.scrapers import matplotlib_scraper
import contextlib
import io
import matplotlib.pyplot as plt
import os
import re

_DARK_STYLE = {'savefig.transparent': True}

_CLASS_OPTION = re.compile(r'(:class:\s*\S+)')
_SRCSET_OPTION = re.compile(r'^[ \t]*:srcset:.*\n', re.MULTILINE)


def _tag_theme(rst: str, theme: str) -> str:
    # Sphinx-Gallery's own "image-sg" directive (used for srcset support)
    # only keeps the first class it is given, which would silently drop the
    # only-light/only-dark class appended below. Fall back to a plain
    # "image" directive, which honors all classes, since srcset support
    # (multiple resolutions per image) is not used in this project anyway.
    rst = rst.replace('.. image-sg::', '.. image::')
    rst = _SRCSET_OPTION.sub('', rst)
    return _CLASS_OPTION.sub(rf'\1 only-{theme}', rst)


def light_dark_scraper(block, block_vars, gallery_conf, **kwargs):
    """Scrape the currently open figures once per theme.

    The example code has already run and produced the figures using the
    default (light) style by the time a scraper is invoked, so those are
    scraped as-is. The dark variant is obtained by re-running the same code
    block under dark-themed Matplotlib rc parameters, which recreates
    equivalent figures using colors appropriate for a dark background.
    """

    if not plt.get_fignums():
        return matplotlib_scraper(block, block_vars, gallery_conf, **kwargs)

    light_rst = _tag_theme(
        matplotlib_scraper(block, block_vars, gallery_conf, **kwargs), 'light'
    )

    src_file = block_vars['src_file']
    code = compile(block.content, src_file, 'exec')
    cwd = os.getcwd()
    os.chdir(os.path.dirname(src_file))

    try:
        with plt.style.context(['dark_background', _DARK_STYLE]):
            with contextlib.redirect_stdout(io.StringIO()):
                exec(code, block_vars['example_globals'])
            dark_rst = _tag_theme(
                matplotlib_scraper(block, block_vars, gallery_conf, **kwargs), 'dark'
            )
    finally:
        os.chdir(cwd)

    return light_rst + dark_rst


# The gallery overview page shows a thumbnail derived from each example's
# first figure (by default). Sphinx-Gallery has no notion of a themed
# thumbnail, so the overview always displayed the light rendering even when
# reading in dark mode. The dark rendering of that same figure is already
# present next to the thumbnail because it is embedded on the example's own
# page, so re-point a copy of each thumbnail at it instead of generating a
# second thumbnail file.
_THUMBNAIL_IMG = re.compile(
    r'<img alt="" src="([^"]*?)sphx_glr_([\w-]+)_thumb\.([a-zA-Z0-9]+)"\s*/>'
)
_SCRAPED_IMAGE = re.compile(r'^sphx_glr_(?P<stem>.+)_(?P<number>\d{3})\.png$')


def _dark_companion(images_dir: str, stem: str) -> str | None:
    """Find the dark counterpart of an example's first (thumbnail) figure.

    Sphinx-Gallery scrapes an example's figures in execution order, all
    rendered with the light style, immediately followed by the same figures
    rendered with the dark style (see ``light_dark_scraper``). So, with `n`
    figures in total, image `1` (the default thumbnail source) and image
    `n + 1` are the light and dark renderings of the same figure. This is
    derived from the files actually produced instead of assuming `n == 1`,
    since an example may plot more than one figure.
    """
    numbers = sorted(
        int(match.group('number'))
        for name in os.listdir(images_dir)
        if (match := _SCRAPED_IMAGE.match(name)) and match.group('stem') == stem
    )
    if len(numbers) < 2 or len(numbers) % 2 != 0:
        return None
    n = len(numbers) // 2
    dark_number = numbers[0] + n
    if dark_number not in numbers:
        return None
    return f'sphx_glr_{stem}_{dark_number:03d}.png'


def _themed_thumbnails(app, pagename, templatename, context, doctree):
    body = context.get('body')
    if not body or 'sphx_glr_' not in body:
        return

    gallery_dirs = app.config.sphinx_gallery_conf['gallery_dirs']
    if isinstance(gallery_dirs, (list, tuple)):
        gallery_dirs = gallery_dirs[0]
    images_dir = os.path.join(app.srcdir, gallery_dirs, 'images')

    def repl(match):
        prefix, stem, ext = match.groups()
        light = (
            f'<img alt="" src="{prefix}sphx_glr_{stem}_thumb.{ext}" '
            'class="only-light" />'
        )
        dark_image = _dark_companion(images_dir, stem)
        if dark_image is None:
            return light
        dark = f'<img alt="" src="{prefix}{dark_image}" class="only-dark" />'
        return light + dark

    context['body'] = _THUMBNAIL_IMG.sub(repl, body)


def setup(app):
    app.connect('html-page-context', _themed_thumbnails)
    return {'parallel_read_safe': True, 'parallel_write_safe': True}
